version = 0.1
[default.deploy.parameters]
stack_name = "ws-serverless-patterns-polling"
resolve_s3 = true
s3_prefix = "ws-serverless-patterns-polling"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "OrdersTablename=\"ws-serverless-patterns-orders-OrdersTable-1KF0C3J5JNA1W\" UserPool=\"eu-west-1_H06ZvUqjr\" Stage=\"dev\""
image_repositories = []
