version = 0.1
[default.deploy.parameters]
stack_name = "ws-serverless-patterns-userprofile"
resolve_s3 = true
s3_prefix = "ws-serverless-patterns-userprofile"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "UserPool=\"eu-west-1_H06ZvUqjr\" Service=\"userprofile\" Stage=\"prod\""
image_repositories = []
